name: Code Checks
on:
  push:
    branches:
      - "ci-check/**"
  pull_request:
    branches: [main, dev]
    types: [opened, synchronize, reopened]
jobs:
  Code-Checks:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ Triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ Running on a ${{ runner.os }} server."
      - run: echo "ğŸ” Branch ${{ github.ref }} from ${{ github.repository }} repo."

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.13.x
          cache: npm

      - name: Install
        run: npm ci

      - name: Linting code...
        run: npm run lint

      - name: Running tests...
        run: npm run test
