# On PR close to dev, publish to npm and version
# with format: 0.0.0-dev.0
name: Dev Release
on:
  push:
    branches:
      - "ci-dev/**"
  pull_request_target:
    branches: [dev]
    types: [closed]

jobs:
  dev-release:
    if: github.event.pull_request.merged == true || github.branch == 'ci-dev/**'
    runs-on: ubuntu-latest
    steps:
      - name: Workflow info
        run: |
          echo "Runner: ${{ github.event_name }}"
          echo "Server OS ${{ runner.os }}"
          echo "Branch ${{ github.ref }} from ${{ github.repository }}."" repo."

      - name: Checkout repo
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 7
      # TODO: use matrix to test on multiple versions of node
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.13.x
          # cache: pnpm #

      - name: Install
        run: pnpm install

      - name: Bump version...
        run: |
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git config --local user.name "$GITHUB_ACTOR"
          pnpm version prerelease --preid dev
          git push --follow-tags

      - name: Publish to npm...
        run: pnpm publish --publish-branch=${{ github.ref_name }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
